version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: app-nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/www.website.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/www.website.com/privkey.pem:/etc/ssl/private/privkey.pem:ro

    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app-backend
    env_file:
      - backend/.env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
